#!/bin/bash -e

# Load docker image and start portainer

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
/bin/bash $INITHOOKS_PATH/bin/portainer.sh 2>&1 | tee /root/portainer-setup.log

